import httpx
import jwt
from fastapi import APIRouter, HTTPException
from ..dependencies import get_secret_key, get_oauth2_scheme
from datetime import datetime, timedelta, timezone
SECRET_KEY = get_secret_key()
router = APIRouter()
oauth2_scheme = get_oauth2_scheme()

async def is_magic_valid(provider : str, access_token : str) -> bool:
    """
    Verify whether a manual magic token generated by a user is valid for a given magic installation.

    Args:
        provider (str): The name of the institution which has installed magic.
        access_token (str): A manually generated magic access token.

    Returns:
        exists (bool): Returns true if the user's access token is valid for the given magic provider.
    """
    async with httpx.AsyncClient(timeout=5) as client:
        response = await client.get(f"https://{provider}.instructure.com/api/v1/users/self", params={
        "access_token":access_token,
        })
    return response.status_code == 200

async def encrypt_magic(magic : str, magic_provider : str | None, expiry : timedelta | None = timedelta(weeks=4)) -> str:
    if magic_provider is None: raise HTTPException(status_code=400, detail="magic_provider must be given when providing a magic")

    legit = await is_magic_valid(magic_provider, magic)

    if not legit:
        raise HTTPException(
            status_code=401,
            detail="Magic is not valid",
            headers={"WWW-Authenticate":"Bearer"}
        )

    data = {"sub":magic}
    if expiry is not None: data["exp"] = datetime.now(timezone.utc) + expiry
    return jwt.encode(data, key=SECRET_KEY, algorithm="HS256")

def decrypt_magic_hash(magic_hash : str) -> str:
    fail = HTTPException(
        status_code = 401,
        detail = "Error decrypting magic. Please make another magic",
        headers = {"WWW-Authenticate":"Bearer"}
        )
    try:
        magic_data = jwt.decode(magic_hash, key=SECRET_KEY, algorithms=["HS256"])
        magic = magic_data.get("sub")
        if not magic: raise fail
    except: raise fail
    return magic
