import httpx
import requests
import json
import pandas as pd
from datetime import datetime, timezone
from fastapi import HTTPException

"""
Decodes Canvas API responses into strings for downstream use.
"""

async def query_canvas(path : str, magic : str, provider : str, params : dict = {}, max_items : int = 100, timeout : int = 60) -> str:
    """
    Obtain data from the Canvas API using a HTTP GET request.
    See https://developerdocs.instructure.com/services/canvas/resources for more information.

    Args:
        path (str): The Canvas v1 API path suffix. E.g., "courses" for "provider.instructure.com/api/v1/courses"
        magic (str): The magic key generated by the wizard to enter the gate.
        provider (str): The name of the institution which has installed Canvas in lowercase.
        params (dict, optional): Additional request parameters for the API to use. Specific to each resource. Defaults to an empty dictionary.
        max_items (int, optional): The maximum number of items to return. Defaults to 100.
        timeout (int, optional): How many seconds to allow the API to respond before timing out. Defaults to 60.

    Raises:
        HTTPException: If the request does not return status 200 or times out, a HTTPException is raised.
    
    Returns:
        data (list[dict]): The response from Canvas as a string.
    """
    params["access_token"] = magic
    params["per_page"] = max_items
    
    path = f"https://{provider}.instructure.com/api/v1/{path}"

    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            response = await client.get(path, params=params)
    except httpx.ReadTimeout:
        raise HTTPException(
            status_code = 408,
            detail = f"{provider.capitalize()} Canvas API GET request timed out after {timeout} seconds. Request URL: {path}"
        ) 
    
    if not response.status_code == 200:
        raise HTTPException(
            status_code = response.status_code,
            detail=response.text
        )

    try:
        content = response.content
        if not content: raise HTTPException(status_code=400, detail="Canvas API response contained no content")
    except: raise HTTPException(status_code=400, detail="Canvas API response contained no content")

    # Canvas API will always respond in JSON format,
    # but we obtain the response in bytes, so it
    # must be decoded into a raw string.
    
    return content.decode('utf-8')
