import os
import jwt
from sqlalchemy.engine import URL
from jwt.exceptions import ExpiredSignatureError
import httpx
from datetime import datetime, timezone, timedelta
from sqlmodel import Session, create_engine, select
from dotenv import load_dotenv
from datetime import timedelta
from fastapi import Depends, HTTPException
from fastapi.security import OAuth2PasswordBearer
from .models import User, UserPublic, University, UniversityCreate, UniversityPublic, UniversityPublicWithAliases, UniversityAliasPublic

load_dotenv()

# Establish a connection to the database.
DB_DRIVER = os.getenv("DB_DRIVER", "mariadb+mariadbconnector")
url = URL.create(
    DB_DRIVER,
    username=os.environ["DB_USER"],
    password=os.environ["DB_PASS"],
    host=os.environ["DB_HOST"],
    database=os.environ["DB_NAME"],
)

engine = create_engine(url, echo=True)

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="login")

def get_engine(): return engine

def get_session():
    with Session(engine) as session:
        yield session

def get_secret_key() -> str:
    key = os.environ["SECRET_KEY"]
    if key is None: raise Exception("HS256 encryption/decryption key not found!")
    return key

def get_oauth2_scheme(): return oauth2_scheme

async def get_current_user(token : str = Depends(oauth2_scheme), session : Session = Depends(get_session)) -> User:
    fail = HTTPException(
        status_code=401,
        detail="Please log in first",
        headers={"WWW-Authenticate":"Bearer"}
    )
    try:
        json_web_token_data = jwt.decode(token, get_secret_key(), algorithms=["HS256"])
    except ExpiredSignatureError:
        raise HTTPException(
            status_code=401,
            detail="Login session has timed out. Please log in again",
            headers={"WWW-Authenticate":"Bearer"}
        )

    username = json_web_token_data.get("sub")
    if username is None: raise fail
    user = session.exec(
        select(User).where(User.username == username)
    ).first()
    if not user: raise fail 
    return user

async def is_magic_valid(provider : str, magic : str, fallback_providers : list[str] = []) -> bool:
    """
    Verify whether a manual magic generated by a user is valid for a given magic installation.

    Args:
        provider (str): The name of the institution which has installed magic.
        magic (str): A manually generated magic.
        fallback_providers (list[str], optional): A list of backup institutions in case the first one fails.

    Returns:
        exists (bool): Returns true if the user's magic is valid for the given magic provider.
    """
    providers = [provider, *fallback_providers]

    for i, provider in enumerate(providers):
        is_last_provider = i == len(providers) - 1

        async with httpx.AsyncClient(timeout=15) as client:
            response = await client.get(f"https://{provider}.instructure.com/api/v1/users/self", params={
            "access_token":magic,
            })

        if response.status_code == 200:
            return True
        
        if is_last_provider:
            return response.status_code == 200

    return False

async def encrypt_magic(
    magic : str,
    university_name : str | None,
    fallback_providers : list[str] = [],
    expiry : timedelta | None = timedelta(weeks=4)
) -> str:
    if university_name is None: raise HTTPException(status_code=400, detail="university_name must be given when providing a magic")
    
    legit = await is_magic_valid(provider=university_name, fallback_providers=fallback_providers, magic=magic)

    if not legit:
        raise HTTPException(
            status_code=401,
            detail="Error: Token is invalid! Check the expiry date is set to a date later than today and try again.",
            headers={"WWW-Authenticate":"Bearer"}
        )

    data = {"sub":magic}
    if expiry is not None: data["exp"] = datetime.now(timezone.utc) + expiry
    return jwt.encode(data, key=get_secret_key(), algorithm="HS256")

def decrypt_magic_hash(magic_hash : str) -> str:
    fail = HTTPException(
        status_code = 401,
        detail = "Your Canvas token has expired! Please create a new one.",
        headers = {"WWW-Authenticate":"Bearer"}
        )
    try:
        magic_data = jwt.decode(magic_hash, key=get_secret_key(), algorithms=["HS256"])
        magic = magic_data.get("sub")
        if not magic: raise fail
    except: raise fail
    return magic

async def get_current_magic(user : User = Depends(get_current_user)) -> str:
    """
    Given a user is logged in, obtain their magic and university_name in plaintext.

    Args:
        user (User): The current logged in user.
    
    Raises:
        HTTPException: If the user does not have a magic or university_name set, raises a 404 Exception.

    Returns:
        magic (str): The user's magic in plaintext.
    """
    magic_hash, university_name = user.magic_hash, user.university_name
    if magic_hash is None: raise HTTPException(status_code=404,detail="User does not have a Canvas token")
    if university_name is None: raise HTTPException(status_code=404, detail="User does not have a university assigned, which is required to obtain their Canvas token")
    magic = decrypt_magic_hash(magic_hash)
    return magic

def create_university_if_not_exists(
    name : str,
    session : Session
):
    """
    Create a new University object or return one if it already exists.

    Args:
        name (str): The name of the university.

    Returns:
        University: The new or existing university.
    """
    name = name.lower().strip()
    existing_university = session.get(University,name)
    if existing_university: return existing_university
    
    new_university = University.model_validate(
        UniversityCreate(name=name).model_dump()
    )
    
    session.add(new_university)
    session.commit()
    session.refresh(new_university)

    new_university = UniversityPublic.model_validate(new_university)

    return new_university

def get_fallback_providers(
    university_name : str | None,
    session : Session
) -> list[str]:
    """
    Obtain a list of fallback Canvas provider names (aliases) for a given university.

    Args:
        university_name (str | None): The university name.
        session (Session): Connection to the database.

    Raises:
        HTTPException: Raises a 404 if the university was not found.

    Returns:
        list[str]: The fallback provider names.
    """

    if university_name is None: return []

    fallback_providers : list[str] = []
    university = session.get(University, university_name)

    if not university: raise HTTPException(status_code=404, detail=f"University not found: {university_name}")

    university = UniversityPublicWithAliases.model_validate(university)
    fallback_provider_objects : list[UniversityAliasPublic] = university.aliases
    fallback_providers = [p.name for p in fallback_provider_objects]
    
    return fallback_providers

def get_fallback_providers_from_user(
    user : User
) -> list[str]:
    """
    Obtain a list of fallback Canvas provider names for a given user.

    Args:
        user (User): The user.

    Returns:
        list[str]: The fallback provider names.
    """
    user_public = UserPublic.model_validate(user)
    fallback_provider_objects : list[UniversityAliasPublic] = user_public.university.aliases
    fallback_providers : list[str] = [p.name for p in fallback_provider_objects]
    return fallback_providers
