from typing import Union

from fastapi import FastAPI
from fastapi.security import OAuth2PasswordBearer

import requests

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.post("/is_token_valid/")
async def is_token_valid(provider : str, access_token : str) -> bool:
    """
    Verify whether a manual Canvas API token generated by a user is valid for a given Canvas installation.

    Args:
        provider (str): The name of the institution which has installed Canvas.
        access_token (str): A manually generated Canvas access token.

    Returns:
        exists (bool): Returns true if the user's access token is valid for the given Canvas provider.
    """
    response = requests.get(f"https://{provider}.instructure.com/api/v1/users/self", params={
        "access_token":access_token,
    })
    return response.status_code == 200

